# Importing Required Libraries

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
%matplotlib inline 

In [2]:
df_train=pd.read_csv("train.csv")
df_test=pd.read_csv("test.csv")

In [3]:
df_train.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

### 1] If for any column(s), the variance is equal to zero, then you need to remove those variable(s).

In [4]:
df_train.var()[df_train.var()==0].index.values

C:\Users\patil.DESKTOP-PMFNMKJ\AppData\Local\Temp\ipykernel_10924\1069090096.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_train.var()[df_train.var()==0].index.values


array(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
       'X293', 'X297', 'X330', 'X347'], dtype=object)

In [5]:
#drop 0 var columns
datafinal=df_train.drop(df_train.var()[df_train.var()==0].index.values, axis=1)
datafinal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 366 entries, ID to X385
dtypes: float64(1), int64(357), object(8)
memory usage: 11.8+ MB


C:\Users\patil.DESKTOP-PMFNMKJ\AppData\Local\Temp\ipykernel_10924\1692636223.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  datafinal=df_train.drop(df_train.var()[df_train.var()==0].index.values, axis=1)


In [6]:
datafinal.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 366 columns]

### 2] Check for null and unique values for test and train sets

In [7]:
df_train.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [8]:
df_test.isnull().sum()

ID      0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 377, dtype: int64

In [9]:
df_train[df_train.isnull().any(axis=1)]

Empty DataFrame
Columns: [ID, y, X0, X1, X2, X3, X4, X5, X6, X8, X10, X11, X12, X13, X14, X15, X16, X17, X18, X19, X20, X21, X22, X23, X24, X26, X27, X28, X29, X30, X31, X32, X33, X34, X35, X36, X37, X38, X39, X40, X41, X42, X43, X44, X45, X46, X47, X48, X49, X50, X51, X52, X53, X54, X55, X56, X57, X58, X59, X60, X61, X62, X63, X64, X65, X66, X67, X68, X69, X70, X71, X73, X74, X75, X76, X77, X78, X79, X80, X81, X82, X83, X84, X85, X86, X87, X88, X89, X90, X91, X92, X93, X94, X95, X96, X97, X98, X99, X100, X101, ...]
Index: []

[0 rows x 378 columns]

In [10]:
df_test[df_test.isnull().any(axis=1)]

Empty DataFrame
Columns: [ID, X0, X1, X2, X3, X4, X5, X6, X8, X10, X11, X12, X13, X14, X15, X16, X17, X18, X19, X20, X21, X22, X23, X24, X26, X27, X28, X29, X30, X31, X32, X33, X34, X35, X36, X37, X38, X39, X40, X41, X42, X43, X44, X45, X46, X47, X48, X49, X50, X51, X52, X53, X54, X55, X56, X57, X58, X59, X60, X61, X62, X63, X64, X65, X66, X67, X68, X69, X70, X71, X73, X74, X75, X76, X77, X78, X79, X80, X81, X82, X83, X84, X85, X86, X87, X88, X89, X90, X91, X92, X93, X94, X95, X96, X97, X98, X99, X100, X101, X102, ...]
Index: []

[0 rows x 377 columns]

#### There are No missing values in train and test data

In [11]:
#get features and labels

features=datafinal.iloc[:,2:]
label=datafinal.iloc[:,1].values

### 3] Apply Label Encoder.

In [12]:
features.head()

X0 X1  X2 X3 X4 X5 X6 X8  X10  X12  ...  X375  X376  X377  X378  X379  \
0   k  v  at  a  d  u  j  o    0    0  ...     0     0     1     0     0   
1   k  t  av  e  d  y  l  o    0    0  ...     1     0     0     0     0   
2  az  w   n  c  d  x  j  x    0    0  ...     0     0     0     0     0   
3  az  t   n  f  d  x  l  e    0    0  ...     0     0     0     0     0   
4  az  v   n  f  d  h  d  n    0    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 364 columns]

In [13]:
label

array([130.81,  88.53,  76.26, ..., 109.22,  87.48, 110.85])

In [14]:
features.describe(include="O")

X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    47    27    44     7     4    29    12    25
top        z    aa    as     c     d     w     g     j
freq     360   833  1659  1942  4205   231  1042   277

In [15]:
#Get only object column names

objcols=features.describe(include=['object']).columns.values
objcols

array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [16]:

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for i in objcols:
  features[i]= le.fit_transform(features[i])

fea=features.values

fea

array([[32, 23, 17, ...,  0,  0,  0],
       [32, 21, 19, ...,  0,  0,  0],
       [20, 24, 34, ...,  0,  0,  0],
       ...,
       [ 8, 23, 38, ...,  0,  0,  0],
       [ 9, 19, 25, ...,  0,  0,  0],
       [46, 19,  3, ...,  0,  0,  0]], dtype=int64)

In [17]:
#Standardize the data using StandardScaler

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
featuresstd = sc.fit_transform(fea)
featuresstd

array([[ 0.16301209,  1.39348787, -0.02812155, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 0.16301209,  1.15902093,  0.15538793, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-0.71055977,  1.51072134,  1.53170902, ..., -0.04081511,
        -0.02180363, -0.03778296],
       ...,
       [-1.58413164,  1.39348787,  1.89872798, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.51133398,  0.924554  ,  0.70591637, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.18217927,  0.924554  , -1.31268791, ..., -0.04081511,
        -0.02180363, -0.03778296]])

### 4] Perform dimensionality reduction

In [18]:
from sklearn.decomposition import PCA

pca = PCA(n_components=364, svd_solver='full')
pca.fit(featuresstd,label)

PCA(n_components=364, svd_solver='full')

In [19]:
print(len(pca.explained_variance_ratio_[pca.explained_variance_ratio_>0.002747252747252748]))

93


In [20]:
#PCA with n components 93 which has explained variance ratio >threshold

pca = PCA(n_components=93,svd_solver='full')
pca.fit(featuresstd,label)

finalFeatures = pca.transform(featuresstd)
finalFeatures.shape

(4209, 93)

In [21]:
finalFeatures

array([[12.25446667, -2.94420951, -0.95784987, ...,  0.86912516,
        -0.73892033, -0.80982148],
       [-0.10254567,  0.36606164,  0.99722405, ...,  0.38555584,
        -2.33082016, -0.62422555],
       [10.27831815, 21.10492781, -5.01329942, ...,  0.08878323,
        -0.28542568, -1.90053779],
       ...,
       [ 0.43696828,  0.89752935,  3.44522225, ..., -0.55307597,
         0.05632946, -0.13451454],
       [-1.34167187,  0.58925266, -0.10965489, ..., -0.75894816,
        -0.12206212,  0.02963942],
       [-2.16821336, -1.06043018, -0.28807512, ..., -0.15311066,
        -0.34216957, -0.3637978 ]])

In [22]:
label.shape

(4209,)

### 5] Predict your test_df values using xgboost

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=123)

In [32]:
X=finalFeatures

In [33]:
y=label

In [34]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3367, 93)
(842, 93)
(3367,)
(842,)


In [39]:
from xgboost import XGBRegressor
    

xgb = XGBRegressor(objective='reg:squarederror', learnning_rate=0.1)
    
xgb.fit(X_train,y_train)

[16:03:09] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-030221e36e1a46bfb-1/xgboost/xgboost-ci-windows/src/learner.cc:767: 
Parameters: { "learnning_rate" } are not used.



XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
             grow_policy='depthwise', importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             learnning_rate=0.1, max_bin=256, max_cat_threshold=64,
             max_cat_to_onehot=4, max_delta_step=0, max_depth=6, max_leaves=0,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=0, num_parallel_tree=1, predictor='auto', ...)

In [40]:
#Check the quality of model
print("Training Accuracy ",model.score(X_train,y_train))
print("Testing Accuracy ",model.score(X_test,y_test))

Training Accuracy  0.9658781068936337
Testing Accuracy  0.47422204239084287


#### The Model is Overfitting